"""add chat sequence ordering

Revision ID: 20260730_0002
Revises: 20260730_0001
Create Date: 2026-07-30
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "20260730_0002"
down_revision: str | None = "20260730_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("chat_sessions", sa.Column("sequence", sa.BigInteger(), nullable=True))
    op.add_column("chat_messages", sa.Column("sequence", sa.BigInteger(), nullable=True))

    op.execute(
        """
        WITH ordered AS (
            SELECT id, row_number() OVER (ORDER BY created_at, id) AS sequence
            FROM chat_sessions
        )
        UPDATE chat_sessions
        SET sequence = ordered.sequence
        FROM ordered
        WHERE chat_sessions.id = ordered.id
        """
    )
    op.execute(
        """
        WITH ordered AS (
            SELECT id, row_number() OVER (ORDER BY created_at, id) AS sequence
            FROM chat_messages
        )
        UPDATE chat_messages
        SET sequence = ordered.sequence
        FROM ordered
        WHERE chat_messages.id = ordered.id
        """
    )

    op.alter_column("chat_sessions", "sequence", nullable=False)
    op.alter_column("chat_messages", "sequence", nullable=False)
    op.execute("ALTER TABLE chat_sessions ALTER COLUMN sequence ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute("ALTER TABLE chat_messages ALTER COLUMN sequence ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        """
        DO $$
        DECLARE next_value bigint;
        BEGIN
            SELECT COALESCE(MAX(sequence), 0) + 1 INTO next_value FROM chat_sessions;
            EXECUTE format('ALTER TABLE chat_sessions ALTER COLUMN sequence RESTART WITH %s', next_value);
        END $$;
        """
    )
    op.execute(
        """
        DO $$
        DECLARE next_value bigint;
        BEGIN
            SELECT COALESCE(MAX(sequence), 0) + 1 INTO next_value FROM chat_messages;
            EXECUTE format('ALTER TABLE chat_messages ALTER COLUMN sequence RESTART WITH %s', next_value);
        END $$;
        """
    )


def downgrade() -> None:
    op.drop_column("chat_messages", "sequence")
    op.drop_column("chat_sessions", "sequence")
